/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratuvar_sonuc_takip;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class AuthorizedOperations extends javax.swing.JFrame {

    /**
     * Creates new form AuthorizedOperations
     */
    public AuthorizedOperations() {
        initComponents();
        jPanel1.setVisible(false);
        PanelBlood.setVisible(false);
        PanelPathology.setVisible(false);
        PanelUrine.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        ustPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PatientIdText = new javax.swing.JTextField();
        AnalysisIdText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AnalysisTypeComboBox = new javax.swing.JComboBox<>();
        AddAnalysisButton = new javax.swing.JButton();
        PatientNameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        GenderCombobox = new javax.swing.JComboBox<>();
        PanelBlood = new javax.swing.JPanel();
        B12Text = new javax.swing.JTextField();
        CholestrolText = new javax.swing.JTextField();
        GlucoseText = new javax.swing.JTextField();
        TriglyceridesText = new javax.swing.JTextField();
        ButonBloodAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        lable6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PanelPathology = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TumorTypeText = new javax.swing.JTextField();
        PieceDiameterText = new javax.swing.JTextField();
        ButonPatholohyAdd = new javax.swing.JButton();
        PanelUrine = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        UrineGlucoseText = new javax.swing.JTextField();
        phText = new javax.swing.JTextField();
        proteinText = new javax.swing.JTextField();
        ButonUrineAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ListPatientsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ustPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Authorized Operations");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratuvar_sonuc_takip/icons/logo.png"))); // NOI18N

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setForeground(new java.awt.Color(153, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratuvar_sonuc_takip/icons/exit.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratuvar_sonuc_takip/icons/DoctorArayuz.png"))); // NOI18N

        javax.swing.GroupLayout ustPanelLayout = new javax.swing.GroupLayout(ustPanel);
        ustPanel.setLayout(ustPanelLayout);
        ustPanelLayout.setHorizontalGroup(
            ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ustPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(139, 139, 139)
                .addGroup(ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ustPanelLayout.setVerticalGroup(
            ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ustPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ustPanelLayout.createSequentialGroup()
                        .addGroup(ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(ustPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ustPanelLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))))
        );

        jButton2.setText("Result Operations");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        PatientIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientIdTextActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Patient ID :");

        jLabel7.setBackground(new java.awt.Color(0, 102, 102));
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Analysis ID :");

        AnalysisTypeComboBox.setForeground(new java.awt.Color(0, 102, 102));
        AnalysisTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Analysis Type...", "Blood Analysis", "Pathology Analysis", "Urine Analysis", " " }));
        AnalysisTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisTypeComboBoxActionPerformed(evt);
            }
        });

        AddAnalysisButton.setText("Add");
        AddAnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAnalysisButtonActionPerformed(evt);
            }
        });

        PatientNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientNameTextActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Patient Name:");

        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Gender:");

        jButton5.setText("See Result");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        GenderCombobox.setForeground(new java.awt.Color(0, 102, 102));
        GenderCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PatientNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(PatientIdText)
                    .addComponent(AnalysisIdText))
                .addGap(111, 111, 111))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(GenderCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(AnalysisTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddAnalysisButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnalysisIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(GenderCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AnalysisTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(AddAnalysisButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        GlucoseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GlucoseTextActionPerformed(evt);
            }
        });

        TriglyceridesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriglyceridesTextActionPerformed(evt);
            }
        });

        ButonBloodAdd.setText("Add");
        ButonBloodAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonBloodAddActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("B12 Value");

        label5.setForeground(new java.awt.Color(0, 102, 102));
        label5.setText("Cholestrol Value");

        lable6.setForeground(new java.awt.Color(0, 102, 102));
        lable6.setText("Glucose Value");

        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Triglycerides Value");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Please enter analysis values..");

        javax.swing.GroupLayout PanelBloodLayout = new javax.swing.GroupLayout(PanelBlood);
        PanelBlood.setLayout(PanelBloodLayout);
        PanelBloodLayout.setHorizontalGroup(
            PanelBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBloodLayout.createSequentialGroup()
                .addGroup(PanelBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBloodLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(ButonBloodAdd))
                    .addGroup(PanelBloodLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(PanelBloodLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(PanelBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBloodLayout.createSequentialGroup()
                                .addGroup(PanelBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lable6)
                                    .addComponent(label5)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(PanelBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(B12Text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CholestrolText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GlucoseText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PanelBloodLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(TriglyceridesText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBloodLayout.setVerticalGroup(
            PanelBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBloodLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B12Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CholestrolText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GlucoseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBloodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TriglyceridesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButonBloodAdd)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        PanelPathology.setForeground(new java.awt.Color(0, 102, 102));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Please enter analysis values..");

        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Tumor Type");

        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Piece Diameter");

        ButonPatholohyAdd.setText("Add");
        ButonPatholohyAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonPatholohyAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPathologyLayout = new javax.swing.GroupLayout(PanelPathology);
        PanelPathology.setLayout(PanelPathologyLayout);
        PanelPathologyLayout.setHorizontalGroup(
            PanelPathologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPathologyLayout.createSequentialGroup()
                .addGroup(PanelPathologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPathologyLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PanelPathologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addGap(16, 16, 16)
                        .addGroup(PanelPathologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TumorTypeText, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(PieceDiameterText)))
                    .addGroup(PanelPathologyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPathologyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButonPatholohyAdd)
                .addGap(63, 63, 63))
        );
        PanelPathologyLayout.setVerticalGroup(
            PanelPathologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPathologyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(PanelPathologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TumorTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelPathologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(PieceDiameterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(ButonPatholohyAdd)
                .addGap(39, 39, 39))
        );

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Please enter analysis values..");

        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Glucose Value");

        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("pH Value");

        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Protein Value");

        ButonUrineAdd.setText("Add");
        ButonUrineAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonUrineAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUrineLayout = new javax.swing.GroupLayout(PanelUrine);
        PanelUrine.setLayout(PanelUrineLayout);
        PanelUrineLayout.setHorizontalGroup(
            PanelUrineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUrineLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(PanelUrineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelUrineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(PanelUrineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UrineGlucoseText, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(phText)
                    .addComponent(proteinText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUrineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButonUrineAdd)
                .addGap(45, 45, 45))
        );
        PanelUrineLayout.setVerticalGroup(
            PanelUrineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUrineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(PanelUrineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(UrineGlucoseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelUrineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(phText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelUrineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(proteinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButonUrineAdd)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ListPatientsButton.setText("List Patients");
        ListPatientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListPatientsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ustPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelPathology, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelUrine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListPatientsButton)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ustPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(ListPatientsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(PanelPathology, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelUrine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AnalysisTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnalysisTypeComboBoxActionPerformed
    PatientInformations pi = new PatientInformations();
    private void AddAnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAnalysisButtonActionPerformed
        

        if (empty()) {
            JOptionPane.showMessageDialog(this, "Please fiil in the blanks");
        } else {
            if (AnalysisTypeComboBox.getSelectedItem() == "Blood Analysis") {
                jPanel1.setVisible(false);
                PanelBlood.setVisible(true);

            } else if (AnalysisTypeComboBox.getSelectedItem() == "Pathology Analysis") {
                jPanel1.setVisible(false);
                PanelPathology.setVisible(true);

            } else if (AnalysisTypeComboBox.getSelectedItem() == "Urine Analysis") {
                jPanel1.setVisible(false);
                PanelUrine.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Please select analysis...");
            }
            clickbCounter = 0;
            clickPCounter = 0;
            clickUCounter = 0;
        }
    }//GEN-LAST:event_AddAnalysisButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel1.setVisible(true);
        PanelBlood.setVisible(false);
        PanelPathology.setVisible(false);
        PanelUrine.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void GlucoseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GlucoseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GlucoseTextActionPerformed
    int clickbCounter = 0;
    private void ButonBloodAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonBloodAddActionPerformed

        clickbCounter++;
        if (clickbCounter < 2) {

            Patient patient = new Patient(PatientIdText.getText(), PatientNameText.getText(), Gender());
            Database.patients.add(patient);

            patient.bloodAnalysis.
                    add(new BloodAnalysis(AnalysisIdText.getText(), B12Text.getText(), CholestrolText.getText(), GlucoseText.getText(), TriglyceridesText.getText()));
        }


    }//GEN-LAST:event_ButonBloodAddActionPerformed
    String Gender() {
        if (GenderCombobox.getSelectedItem() == "Male") {
            return "Male";
        } else {
            return "Female";
        }

    }

    boolean empty() {
        if (PatientNameText.getText().length() > 0 && PatientIdText.getText().length() > 0 && AnalysisIdText.getText().length() > 0) {
            return false;

        } else {
            return true;
        }
    }
    private void PatientIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientIdTextActionPerformed

    }//GEN-LAST:event_PatientIdTextActionPerformed
    int clickPCounter = 0;
    private void ButonPatholohyAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonPatholohyAddActionPerformed
        clickPCounter++;
        if (clickPCounter < 2) {
            Patient patient = new Patient(PatientIdText.getText(), PatientNameText.getText(), Gender());
            Database.patients.add(patient);
            patient.pathologyAnalysis.add(new PathologyAnalysis(AnalysisIdText.getText(), PieceDiameterText.getText(), TumorTypeText.getText()));
        }

    }//GEN-LAST:event_ButonPatholohyAddActionPerformed
    int clickUCounter = 0;
    private void ButonUrineAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonUrineAddActionPerformed
        clickUCounter++;
        if (clickUCounter < 2) {
            Patient patient = new Patient(PatientIdText.getText(), PatientNameText.getText(), Gender());
            Database.patients.add(patient);
            patient.urineAnalysis.add(new UrineAnalysis(AnalysisIdText.getText(), phText.getText(), proteinText.getText(), GlucoseText.getText()));
        }
    }//GEN-LAST:event_ButonUrineAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Authorized a = new Authorized();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ResultFrame rf = new ResultFrame();
        rf.dtm.addColumn("Patient Name");
        if (AnalysisTypeComboBox.getSelectedItem() == ("Blood Analysis")) {
            for (int i = 0; i < Database.patients.size(); i++) {
                Patient patient = Database.patients.get(i);
                for (int j = 0; j < patient.bloodAnalysis.size(); j++) {
                    if (patient.patientID.equals(PatientIdText.getText()) && patient.bloodAnalysis.get(j).analysisID.equals(AnalysisIdText.getText())) {
                        for (int k = 0; k < patient.bloodAnalysis.get(j).analysisName.length; k++) {
                            if (rf.dtm.getColumnCount() < patient.bloodAnalysis.get(j).analysisName.length + 1) {
                                rf.dtm.addColumn(patient.bloodAnalysis.get(j).analysisName[k]);
                            }

                        }
                        rf.dtm.addRow(new Object[]{patient.patientName, patient.bloodAnalysis.get(j).analysisValues.get(0), patient.bloodAnalysis.get(j).analysisValues.get(1),
                            patient.bloodAnalysis.get(j).analysisValues.get(2), patient.bloodAnalysis.get(j).analysisValues.get(3)});

                    }
                }

            }
            rf.setVisible(true);
        } else if (AnalysisTypeComboBox.getSelectedItem() == ("Pathology Analysis")) {
            for (int i = 0; i < Database.patients.size(); i++) {
                Patient patient = Database.patients.get(i);

                for (int j = 0; j < patient.pathologyAnalysis.size(); j++) {
                    if (patient.patientID.equals(PatientIdText.getText()) && patient.pathologyAnalysis.get(j).analysisID.equals(AnalysisIdText.getText())) {

                        for (int k = 0; k < patient.pathologyAnalysis.get(j).analysisName.length; k++) {
                            if (rf.dtm.getColumnCount() < patient.pathologyAnalysis.get(j).analysisName.length + 1) {
                                rf.dtm.addColumn(patient.pathologyAnalysis.get(j).analysisName[k]);
                            }
                        }
                        rf.dtm.addRow(new Object[]{patient.patientName, patient.pathologyAnalysis.get(j).analysisValues.get(0), patient.pathologyAnalysis.get(j).analysisValues.get(1)});
                    }
                }
            }
            rf.setVisible(true);
        } else if (AnalysisTypeComboBox.getSelectedItem() == ("Urine Analysis")) {
            for (int i = 0; i < Database.patients.size(); i++) {
                Patient patient = Database.patients.get(i);

                for (int j = 0; j < patient.urineAnalysis.size(); j++) {
                    if (patient.patientID.equals(PatientIdText.getText()) && patient.urineAnalysis.get(j).analysisID.equals(AnalysisIdText.getText())) {

                        for (int k = 0; k < patient.urineAnalysis.get(j).analysisName.length; k++) {

                            if (rf.dtm.getColumnCount() < patient.urineAnalysis.get(j).analysisName.length + 1) {
                                rf.dtm.addColumn(patient.urineAnalysis.get(j).analysisName[k]);
                            }
                        }
                        rf.dtm.addRow(new Object[]{patient.patientName, patient.urineAnalysis.get(j).analysisValues.get(0), patient.urineAnalysis.get(j).analysisValues.get(1), patient.urineAnalysis.get(j).analysisValues.get(2)});
                    }
                }
            }
            rf.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No Records Found...");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void ListPatientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListPatientsButtonActionPerformed
        PatientInformations pi = new PatientInformations();
        pi.setVisible(true);
        dispose();

    }//GEN-LAST:event_ListPatientsButtonActionPerformed

    private void TriglyceridesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriglyceridesTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TriglyceridesTextActionPerformed

    private void PatientNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientNameTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthorizedOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthorizedOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthorizedOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthorizedOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthorizedOperations().setVisible(true);
            }
        });
    }

    void setPatientID() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAnalysisButton;
    private javax.swing.JTextField AnalysisIdText;
    private javax.swing.JComboBox<String> AnalysisTypeComboBox;
    private javax.swing.JTextField B12Text;
    private javax.swing.JButton ButonBloodAdd;
    private javax.swing.JButton ButonPatholohyAdd;
    private javax.swing.JButton ButonUrineAdd;
    private javax.swing.JTextField CholestrolText;
    private javax.swing.JComboBox<String> GenderCombobox;
    private javax.swing.JTextField GlucoseText;
    private javax.swing.JButton ListPatientsButton;
    private javax.swing.JPanel PanelBlood;
    private javax.swing.JPanel PanelPathology;
    private javax.swing.JPanel PanelUrine;
    private javax.swing.JTextField PatientIdText;
    private javax.swing.JTextField PatientNameText;
    private javax.swing.JTextField PieceDiameterText;
    private javax.swing.JTextField TriglyceridesText;
    private javax.swing.JTextField TumorTypeText;
    private javax.swing.JTextField UrineGlucoseText;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel lable6;
    private javax.swing.JTextField phText;
    private javax.swing.JTextField proteinText;
    private javax.swing.JPanel ustPanel;
    // End of variables declaration//GEN-END:variables
}
